### ISSUE TITLE
BUG: No notification when audio playing

### ISSUE THREAD

**Issue by kurtismash** [InsanityRadio/Player-Mobile#6]
Android 8.1.0, no notification is created when the app is running in the background or in foreground and playing audio.

**Comment by Jamie0** [comment]
This issue has been fixed in the next pre-release by changing the target SDK version from 26 to 25. This is due to a change in how Android's notification system works. `react-native-music-controls` don't seem to provide the notification channel ID (logcat suggests it is null), which now seems to be required for its notification/widget to show up. 

To install the new pre-releases, you'll need to uninstall the original application. This is because Android doesn't allow you to downgrade target SDK versions easily. 

Having the notification seems to be how Android communicates system events to an app, like use of remote controls on headphones, headphone unplug, so fixing this widget fixes the other issues. 

Closing as fixed.
